<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            
            // Productos de la categoría "Aros" para Automoviles (category_id = 1)
            [
                'sku' => 1001,
                'name' => 'Aros Deportivos OZ Racing',
                'description' => 'Aros de diseño deportivo y peso ligero.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 300.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1002,
                'name' => 'Aros de Aleación BBS',
                'description' => 'Aros de alta calidad y resistencia.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 320.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1003,
                'name' => 'Aros Enkei Tuning',
                'description' => 'Aros diseñados para autos de alto rendimiento.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 310.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1004,
                'name' => 'Aros RAYS Gram Lights',
                'description' => 'Aros ultraligeros para máxima agilidad.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 350.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1005,
                'name' => 'Aros American Racing Vintage',
                'description' => 'Aros clásicos para un toque retro.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 290.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1006,
                'name' => 'Aros Borbet Luxury',
                'description' => 'Aros de lujo con diseño elegante.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 400.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1007,
                'name' => 'Aros MOMO Hyperstar',
                'description' => 'Aros deportivos con excelente acabado.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 360.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1008,
                'name' => 'Aros Rotiform Aerodiscs',
                'description' => 'Aros innovadores con diseño distintivo.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 330.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1009,
                'name' => 'Aros Fuel Off-Road',
                'description' => 'Aros para vehículos todo terreno.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 340.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1010,
                'name' => 'Aros SSR Formula Mesh',
                'description' => 'Aros de alta gama para autos deportivos.',
                'image_path' => 'products/aroautomovil.jpg',
                'price' => 370.0,
                'category_id' => 1,
            ],

            // Productos de la categoría "Aros" para Suv / Crossover (category_id = 2)
            [
                'sku' => 1011,
                'name' => 'Aros Deportivos OZ Racing',
                'description' => 'Aros de diseño deportivo y peso ligero.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 300.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1012,
                'name' => 'Aros de Aleación BBS',
                'description' => 'Aros de alta calidad y resistencia.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 320.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1013,
                'name' => 'Aros Enkei Tuning',
                'description' => 'Aros diseñados para autos de alto rendimiento.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 310.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1014,
                'name' => 'Aros RAYS Gram Lights',
                'description' => 'Aros ultraligeros para máxima agilidad.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 350.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1015,
                'name' => 'Aros American Racing Vintage',
                'description' => 'Aros clásicos para un toque retro.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 290.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1016,
                'name' => 'Aros Borbet Luxury',
                'description' => 'Aros de lujo con diseño elegante.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 400.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1017,
                'name' => 'Aros MOMO Hyperstar',
                'description' => 'Aros deportivos con excelente acabado.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 360.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1018,
                'name' => 'Aros Rotiform Aerodiscs',
                'description' => 'Aros innovadores con diseño distintivo.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 330.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1019,
                'name' => 'Aros Fuel Off-Road',
                'description' => 'Aros para vehículos todo terreno.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 340.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1020,
                'name' => 'Aros SSR Formula Mesh',
                'description' => 'Aros de alta gama para autos deportivos.',
                'image_path' => 'products/arosuvcrossover.jpg',
                'price' => 370.0,
                'category_id' => 1,
            ],

            // Productos de la categoría "Aros" para Camionetas (category_id = 1)
            [
                'sku' => 1021,
                'name' => 'Aros Deportivos OZ Racing',
                'description' => 'Aros de diseño deportivo y peso ligero.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 300.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1022,
                'name' => 'Aros de Aleación BBS',
                'description' => 'Aros de alta calidad y resistencia.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 310.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1023,
                'name' => 'Aros Enkei Tuning',
                'description' => 'Aros diseñados para autos de alto rendimiento.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 310.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1024,
                'name' => 'Aros RAYS Gram Lights',
                'description' => 'Aros ultraligeros para máxima agilidad.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 350.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1025,
                'name' => 'Aros American Racing Vintage',
                'description' => 'Aros clásicos para un toque retro.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 190.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1026,
                'name' => 'Aros Borbet Luxury',
                'description' => 'Aros de lujo con diseño elegante.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 400.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1027,
                'name' => 'Aros MOMO Hyperstar',
                'description' => 'Aros deportivos con excelente acabado.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 360.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1028,
                'name' => 'Aros Rotiform Aerodiscs',
                'description' => 'Aros innovadores con diseño distintivo.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 330.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1029,
                'name' => 'Aros Fuel Off-Road',
                'description' => 'Aros para vehículos todo terreno.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 340.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1030,
                'name' => 'Aros SSR Formula Mesh',
                'description' => 'Aros de alta gama para autos deportivos.',
                'image_path' => 'products/arocamioneta.jpg',
                'price' => 370.0,
                'category_id' => 1,
            ],

            // Productos de la categoría "Aros" para Vans / Comerciales Ligeros (category_id = 1)
            [
                'sku' => 1031,
                'name' => 'Aros Deportivos OZ Racing',
                'description' => 'Aros de diseño deportivo y peso ligero.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 300.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1032,
                'name' => 'Aros de Aleación BBS',
                'description' => 'Aros de alta calidad y resistencia.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 310.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1033,
                'name' => 'Aros Enkei Tuning',
                'description' => 'Aros diseñados para autos de alto rendimiento.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 310.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1034,
                'name' => 'Aros RAYS Gram Lights',
                'description' => 'Aros ultraligeros para máxima agilidad.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 350.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1035,
                'name' => 'Aros American Racing Vintage',
                'description' => 'Aros clásicos para un toque retro.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 290.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1036,
                'name' => 'Aros Borbet Luxury',
                'description' => 'Aros de lujo con diseño elegante.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 400.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1037,
                'name' => 'Aros MOMO Hyperstar',
                'description' => 'Aros deportivos con excelente acabado.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 360.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1038,
                'name' => 'Aros Rotiform Aerodiscs',
                'description' => 'Aros innovadores con diseño distintivo.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 330.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1039,
                'name' => 'Aros Fuel Off-Road',
                'description' => 'Aros para vehículos todo terreno.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 340.0,
                'category_id' => 1,
            ],
            [
                'sku' => 1040,
                'name' => 'Aros SSR Formula Mesh',
                'description' => 'Aros de alta gama para autos deportivos.',
                'image_path' => 'products/arovanscomercialesligeros.jpg',
                'price' => 370.0,
                'category_id' => 1,
            ],

            // Productos de la categoría "Llantas" para aútomoviles (category_id = 2)
            [
                'sku' => 2001,
                'name' => 'Llantas Triangle',
                'description' => 'Llantas de alta resistencia para terrenos irregulares.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 150.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2002,
                'name' => 'Llantas Radiales Michelin',
                'description' => 'Llantas deportivas de alta calidad',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 200.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2003,
                'name' => 'Llantas Bridgestone Potenza',
                'description' => 'Llantas deportivas de alta velocidad.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 220.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2004,
                'name' => 'Llantas Pirelli Scorpion',
                'description' => 'Llantas todo terreno con gran durabilidad.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 280.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2005,
                'name' => 'Llantas Goodyear EfficientGrip',
                'description' => 'Llantas de alto rendimiento y bajo ruido.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 220.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2006,
                'name' => 'Llantas Hankook Ventus',
                'description' => 'Llantas premium para un manejo suave.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 290.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2007,
                'name' => 'Llantas Yokohama Geolandar',
                'description' => 'Llantas todoterreno con excelente tracción.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 270.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2008,
                'name' => 'Llantas Continental PremiumContact',
                'description' => 'Llantas seguras y confiables para todas las estaciones.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 230.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2009,
                'name' => 'Llantas Firestone Destination',
                'description' => 'Llantas duraderas para condiciones difíciles.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 260.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2010,
                'name' => 'Llantas Dunlop Grandtrek',
                'description' => 'Llantas ideales para SUV y 4x4.',
                'image_path' => 'products/llantaautomovil.jpg',
                'price' => 275.0,
                'category_id' => 2,
            ],

            // Productos de la categoría "Llantas" para Suv / Crossover (category_id = 2)
            [
                'sku' => 2011,
                'name' => 'Llantas Triangle',
                'description' => 'Llantas de alta resistencia para terrenos irregulares.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 150.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2012,
                'name' => 'Llantas Radiales Michelin',
                'description' => 'Llantas deportivas de alta calidad',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 200.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2013,
                'name' => 'Llantas Bridgestone Potenza',
                'description' => 'Llantas deportivas de alta velocidad.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 220.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2014,
                'name' => 'Llantas Pirelli Scorpion',
                'description' => 'Llantas todo terreno con gran durabilidad.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 280.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2015,
                'name' => 'Llantas Goodyear EfficientGrip',
                'description' => 'Llantas de alto rendimiento y bajo ruido.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 220.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2016,
                'name' => 'Llantas Hankook Ventus',
                'description' => 'Llantas premium para un manejo suave.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 290.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2017,
                'name' => 'Llantas Yokohama Geolandar',
                'description' => 'Llantas todoterreno con excelente tracción.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 270.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2018,
                'name' => 'Llantas Continental PremiumContact',
                'description' => 'Llantas seguras y confiables para todas las estaciones.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 230.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2019,
                'name' => 'Llantas Firestone Destination',
                'description' => 'Llantas duraderas para condiciones difíciles.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 160.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2020,
                'name' => 'Llantas Dunlop Grandtrek',
                'description' => 'Llantas ideales para SUV y 4x4.',
                'image_path' => 'products/llantasuvcrossover.jpg',
                'price' => 275.0,
                'category_id' => 2,
            ],

            // Productos de la categoría "Llantas" para Camionetas (category_id = 2)
            [
                'sku' => 2021,
                'name' => 'Llantas Triangle',
                'description' => 'Llantas de alta resistencia para terrenos irregulares.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 150.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2022,
                'name' => 'Llantas Radiales Michelin',
                'description' => 'Llantas deportivas de alta calidad',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 200.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2023,
                'name' => 'Llantas Bridgestone Potenza',
                'description' => 'Llantas deportivas de alta velocidad.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 220.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2024,
                'name' => 'Llantas Pirelli Scorpion',
                'description' => 'Llantas todo terreno con gran durabilidad.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 280.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2025,
                'name' => 'Llantas Goodyear EfficientGrip',
                'description' => 'Llantas de alto rendimiento y bajo ruido.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 220.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2026,
                'name' => 'Llantas Hankook Ventus',
                'description' => 'Llantas premium para un manejo suave.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 290.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2027,
                'name' => 'Llantas Yokohama Geolandar',
                'description' => 'Llantas todoterreno con excelente tracción.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 270.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2028,
                'name' => 'Llantas Continental PremiumContact',
                'description' => 'Llantas seguras y confiables para todas las estaciones.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 230.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2029,
                'name' => 'Llantas Firestone Destination',
                'description' => 'Llantas duraderas para condiciones difíciles.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 260.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2030,
                'name' => 'Llantas Dunlop Grandtrek',
                'description' => 'Llantas ideales para SUV y 4x4.',
                'image_path' => 'products/llantacamioneta.jpg',
                'price' => 275.0,
                'category_id' => 2,
            ],

            // Productos de la categoría "Llantas" para Vans / Comerciales Ligeros (category_id = 2)
            [
                'sku' => 2031,
                'name' => 'Llantas Triangle',
                'description' => 'Llantas de alta resistencia para terrenos irregulares.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 150.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2032,
                'name' => 'Llantas Radiales Michelin',
                'description' => 'Llantas deportivas de alta calidad',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 200.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2033,
                'name' => 'Llantas Bridgestone Potenza',
                'description' => 'Llantas deportivas de alta velocidad.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 220.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2034,
                'name' => 'Llantas Pirelli Scorpion',
                'description' => 'Llantas todo terreno con gran durabilidad.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 280.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2035,
                'name' => 'Llantas Goodyear EfficientGrip',
                'description' => 'Llantas de alto rendimiento y bajo ruido.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 220.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2036,
                'name' => 'Llantas Hankook Ventus',
                'description' => 'Llantas premium para un manejo suave.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 290.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2037,
                'name' => 'Llantas Yokohama Geolandar',
                'description' => 'Llantas todoterreno con excelente tracción.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 270.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2038,
                'name' => 'Llantas Continental PremiumContact',
                'description' => 'Llantas seguras y confiables para todas las estaciones.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 230.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2039,
                'name' => 'Llantas Firestone Destination',
                'description' => 'Llantas duraderas para condiciones difíciles.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 260.0,
                'category_id' => 2,
            ],
            [
                'sku' => 2040,
                'name' => 'Llantas Dunlop Grandtrek',
                'description' => 'Llantas ideales para SUV y 4x4.',
                'image_path' => 'products/llantavanscomercialesligeros.jpg',
                'price' => 275.0,
                'category_id' => 2,
            ],

            // Productos de la categoría "Baterías" para Automoviles (category_id = 3)
            [
                'sku' => 3001,
                'name' => 'Batería Bosch S5',
                'description' => 'Batería de alta duración y rendimiento.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 120.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3002,
                'name' => 'Batería AC Delco Professional',
                'description' => 'Batería de alto rendimiento para condiciones extremas.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 130.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3003,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3004,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],

            [
                'sku' => 3005,
                'name' => 'Batería Bosch S5',
                'description' => 'Batería de alta duración y rendimiento.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 120.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3006,
                'name' => 'Batería AC Delco Professional',
                'description' => 'Batería de alto rendimiento para condiciones extremas.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 130.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3007,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3008,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3009,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3010,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriaautomovil.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],
            
            // Productos de la categoría "Baterías" para Suv / Crossover (category_id = 3)
            [
                'sku' => 3011,
                'name' => 'Batería Bosch S5',
                'description' => 'Batería de alta duración y rendimiento.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 120.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3012,
                'name' => 'Batería AC Delco Professional',
                'description' => 'Batería de alto rendimiento para condiciones extremas.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 130.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3013,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3014,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],

            [
                'sku' => 3015,
                'name' => 'Batería Bosch S5',
                'description' => 'Batería de alta duración y rendimiento.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 120.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3016,
                'name' => 'Batería AC Delco Professional',
                'description' => 'Batería de alto rendimiento para condiciones extremas.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 130.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3017,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3018,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3019,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3020,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriasuvcrossover.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],

            // Productos de la categoría "Baterías" para Camionetas (category_id = 3)
            [
                'sku' => 3021,
                'name' => 'Batería Bosch S5',
                'description' => 'Batería de alta duración y rendimiento.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 120.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3022,
                'name' => 'Batería AC Delco Professional',
                'description' => 'Batería de alto rendimiento para condiciones extremas.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 130.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3023,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3024,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],

            [
                'sku' => 3025,
                'name' => 'Batería Bosch S5',
                'description' => 'Batería de alta duración y rendimiento.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 120.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3026,
                'name' => 'Batería AC Delco Professional',
                'description' => 'Batería de alto rendimiento para condiciones extremas.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 130.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3027,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3028,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3029,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3030,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriacamioneta.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],

            // Productos de la categoría "Baterías" para Vans / Comerciales Ligeros (category_id = 3)
            [
                'sku' => 3031,
                'name' => 'Batería Bosch S5',
                'description' => 'Batería de alta duración y rendimiento.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 120.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3032,
                'name' => 'Batería AC Delco Professional',
                'description' => 'Batería de alto rendimiento para condiciones extremas.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 130.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3033,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3034,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],

            [
                'sku' => 3035,
                'name' => 'Batería Bosch S5',
                'description' => 'Batería de alta duración y rendimiento.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 120.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3036,
                'name' => 'Batería AC Delco Professional',
                'description' => 'Batería de alto rendimiento para condiciones extremas.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 130.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3037,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3038,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3039,
                'name' => 'Batería LTH Powerframe',
                'description' => 'Batería confiable con tecnología avanzada.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 110.0,
                'category_id' => 3,
            ],
            [
                'sku' => 3040,
                'name' => 'Batería Optima YellowTop',
                'description' => 'Batería para sistemas de alta demanda.',
                'image_path' => 'products/bateriavanscomercialesligeros.jpg',
                'price' => 150.0,
                'category_id' => 3,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
